### PR TITLE
Requirements: remove python2 only dependencies 

### PR DESCRIPTION
**Pull request by blshkv**
https://pypi.org/project/ipaddress/
Port of the 3.3+ ipaddress module to 2.6, 2.7, 3.2

### CODE REVIEW

**Comment by blshkv** [comment]
"configparser" as well

**Comment by mh4x0f** [comment]
totally baseless, both modules are available for python3 including only for python3

**Comment by blshkv** [comment]
They might be available as 3.2 modules but not required for the python3.7 and above. These are backports, it is clearly stated in the description.

Please re-consider

**Comment by blshkv** [comment]
Ping?

**Pull request closed without merging**
